version: '3'
services:
  oef-node:
    image: "qati/oef:latest"
    ports:
      - "3333:3333"
      - "20000:20000"
      - "40000:40000"
    networks:
      main_net:
        ipv4_address: 172.28.1.1
    logging:
      driver: none
    entrypoint:
      - "/bin/sh"
      - "/app/oef.sh"
      - "node"
      - "no_sh"
      - "--node_key"
      - "Search1"
      - "--core_key"
      - "Core1"
      - "--search_port"
      - "20000"
      - "--core_port"
      - "3333"
      - "--dap_port"
      - "30000"
      - "--director_api_port"
      - "40000"

  visdom:
    image: "hypnosapos/visdom:latest"
    ports:
      - "8097:8097"
    networks:
      main_net:
        ipv4_address: 172.28.1.2


  baseline:
    image: "baseline-image"
    env_file:
      - .env
    depends_on:
      - oef-node
    volumes:
      - ../:/build
    build:
      context: ../
      dockerfile: docker-tac-develop/Dockerfile
    networks:
      main_net:
        ipv4_address: 172.28.1.3
    entrypoint:
      - "pipenv"
      - "run"
      - "python3"
      - "examples/simulation_demo/tac_agent_spawner.py"
      - "--nb-agents"
      - "${NB_AGENTS}"
      - "--nb-goods"
      - "${NB_GOODS}"
      - "--nb-baseline-agents"
      - "${NB_BASELINE_AGENTS}"
      - "--oef-addr"
      - "${OEF_ADDR}"
      - "--oef-port"
      - "${OEF_PORT}"
      - "--uml"
      - "${UML}"
      - "--data-output-dir"
      - "${DATA_OUTPUT_DIR}"
      - "--experiment-id"
      - "${EXPERIMENT_ID}"
      - "--plot"
      - "${PLOT}"
      - "--lower-bound-factor"
      - "${LOWER_BOUND_FACTOR}"
      - "--upper-bound-factor"
      - "${UPPER_BOUND_FACTOR}"
      - "--tx-fee"
      - "${TX_FEE}"
      - "--registration-timeout"
      - "${REGISTRATION_TIMEOUT}"
      - "--inactivity-timeout"
      - "${INACTIVITY_TIMEOUT}"
      - "--competition-timeout"
      - "${COMPETITION_TIMEOUT}"
      - "--gui"
      - "--visdom-addr"
      - "172.28.1.2"
      - "--visdom-port"
      - "8097"
      - "--seed"
      - "${SEED}"
networks:
    main_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16


